from src.database.config import DataConfig

if DataConfig.Local:
    from src.database.api_client import LocalData as API
else:
    from src.database.api_client import Requests as API


class Data:
    def __init__(self) -> None:
        self.info = None
        if DataConfig.RamData:
            self.set_info()

    def set_info(self):
        self.info = API.get_full_info()

    def get_info(self, user):
        if DataConfig.RamData:
            return self.info[user]
        else:
            return API.get_info(user)

    def save_autogenerated_data(user):
        pass

data = Data()